changesetIgnorePatterns:
  - "**/*.test.{js,ts}"

enableGlobalCache: false

immutablePatterns:
  - .pnp.*

initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  gatsby-cli@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      react: "*"
      webpack: "*"
  gatsby-recipes@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      ink: "*"
      react: "*"
      webpack: "*"
  gatsby@*:
    peerDependencies:
      "@babel/core": "*"
  monaco-editor-webpack-plugin@*:
    dependencies:
      webpack: ^4.5.0
  typedoc@*:
    peerDependenciesMeta:
      "@strictsoftware/typedoc-plugin-monorepo":
        optional: true
      typedoc-neo-theme:
        optional: true
      typedoc-plugin-yarn:
        optional: true

preferInteractive: true

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js

cacheParameters:
  matrix:
    platform: [darwin, linux, windows, freebsd, openbsd]
    arch: [32, 64, arm, arm64, mips64le, ppc64le]
